### ISSUE TITLE
testinggggg detail

### ISSUE THREAD

**Issue by gitdoer** [gitdoapp/testing#539]
asdgasdgasgasdgas

**Comment by pepibumur** [comment]
@isaacroldan creating a comment from iPhone

**Comment by pepibumur** [comment]
@VicenteBorrell lo vamos a petar! ya estoy escribiendo comentarios desde el iPhone :)

**Comment by pepibumur** [comment]
testing issues #483

**Comment by pepibumur** [comment]
asga  asga gasgas

**Comment by pepibumur** [comment]
pim pam pu
