### ISSUE TITLE
Test Issue 🤓

### ISSUE THREAD

**Issue by VicenteBorrell** [gitdoapp/testing#721]

**Comment by pepibumur** [comment]
Does it work @VicenteBorrell ?

**Comment by VicenteBorrell** [comment]
Yep @pepibumur , this is awesome!

**Comment by pepibumur** [comment]
@VicenteBorrell I didn't get any push notification 😞

**Comment by VicenteBorrell** [comment]
Editing the title worked @pepibumur !

**Comment by pepibumur** [comment]
Ohhh me llegó la push @VicenteBorrell
