### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by gitdoer** [gitdoapp/testing#965]

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-3731944465.jpg)

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-3844974265.jpg)

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-3677085635.jpg)

**Testing how it works**
- Olga
- k

 # asdgasdgas

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-4090434088.jpg)

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-1522441351.jpg)

**Comment by gitdoer** [comment]
@nandodelauni

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-318094553.jpg)

**Comment by pepibumur** [comment]
Bibg

**Comment by pepibumur** [comment]
Hihh

**Comment by pepibumur** [comment]
Bhb
