### ISSUE TITLE
Okayama

### ISSUE THREAD

**Issue by gitdoer** [gitdoapp/testing#966]

**Comment by gitdoer** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-2940971712.jpg)

**Comment by pepibumur** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160306-4281900787.jpg)

**Comment by pepibumur** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160308-2168900180.jpg)

**Comment by pepibumur** [comment]
![image](https://s3.amazonaws.com/gitdoimages/20160308-3974157954.jpg)
